server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_api?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      demon:
        exam: debug